"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
Given two positive integers A and B, find the number of Fibonacci numbers between A and B.
"""

# LANGUAGE: Python
# AUTHOR: Inventrohyder
# GITHUB: https://github.com/inventrohyder/

def fibonacci(a, b):
    fib_nums = [1, 2]
    while(fib_nums[-1] < b):
        fib_nums.append(fib_nums[-2] + fib_nums[-1])
    while(fib_nums[-1] > b):
        fib_nums.pop()
    while(len(fib_nums) is not 0 and fib_nums[0] < a):
        fib_nums = fib_nums[1:]
    return len(fib_nums)
